# Site settings
title: Adam Isaak - Dev
description: A personal portfolio of all the cool things I did
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Adam Isaak
user_description:  Greetings, I'm Adam, a Software Developer from Winnipeg. If you want to know what I'm usually up to it's either coding away on whatever school or personal project that's currently in my sights at my computer, or I'm prepping for my weekly D&D game... Also at my computer. Joking aside I love to create things that people enjoy and can experience. It's what drives me to learn new technologies and develop new solutions. If you want to know what I've done and what I'm good at keep on scrolling down and take a look, or swing by my LinkedIn or Github pages. Thanks for stopping on by!
user_title: Software Developer
email: adam.isaak.dev@gmail.com
github_username:  Adam-Isaak-dev
linkedin__username: Adam Isaak

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
